[project]
name = "vitacrew"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "crewai>=0.5.0",
    "pydantic>=2.10.4",
    "pytest>=8.3.4",
    "pytest-asyncio>=0.25.2",
    "streamlit>=1.41.1",
]
